// Admin Dashboard Stats
export const GET_ADMIN_STATS_REQUEST = 'GET_ADMIN_STATS_REQUEST';
export const GET_ADMIN_STATS_SUCCESS = 'GET_ADMIN_STATS_SUCCESS';
export const GET_ADMIN_STATS_FAILURE = 'GET_ADMIN_STATS_FAILURE';

// Admin Products
export const GET_ADMIN_PRODUCTS_REQUEST = 'GET_ADMIN_PRODUCTS_REQUEST';
export const GET_ADMIN_PRODUCTS_SUCCESS = 'GET_ADMIN_PRODUCTS_SUCCESS';
export const GET_ADMIN_PRODUCTS_FAILURE = 'GET_ADMIN_PRODUCTS_FAILURE';

export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_FAILURE = 'CREATE_PRODUCT_FAILURE';

export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILURE = 'DELETE_PRODUCT_FAILURE';

// Admin Orders
export const GET_ADMIN_ORDERS_REQUEST = 'GET_ADMIN_ORDERS_REQUEST';
export const GET_ADMIN_ORDERS_SUCCESS = 'GET_ADMIN_ORDERS_SUCCESS';
export const GET_ADMIN_ORDERS_FAILURE = 'GET_ADMIN_ORDERS_FAILURE';

export const UPDATE_ORDER_STATUS_REQUEST = 'UPDATE_ORDER_STATUS_REQUEST';
export const UPDATE_ORDER_STATUS_SUCCESS = 'UPDATE_ORDER_STATUS_SUCCESS';
export const UPDATE_ORDER_STATUS_FAILURE = 'UPDATE_ORDER_STATUS_FAILURE';

export const DELETE_ORDER_REQUEST = 'DELETE_ORDER_REQUEST';
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS';
export const DELETE_ORDER_FAILURE = 'DELETE_ORDER_FAILURE';

// Admin Users
export const GET_ADMIN_USERS_REQUEST = 'GET_ADMIN_USERS_REQUEST';
export const GET_ADMIN_USERS_SUCCESS = 'GET_ADMIN_USERS_SUCCESS';
export const GET_ADMIN_USERS_FAILURE = 'GET_ADMIN_USERS_FAILURE';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

// Sales Report
export const GET_SALES_REPORT_REQUEST = 'GET_SALES_REPORT_REQUEST';
export const GET_SALES_REPORT_SUCCESS = 'GET_SALES_REPORT_SUCCESS';
export const GET_SALES_REPORT_FAILURE = 'GET_SALES_REPORT_FAILURE';